# Generated by Django 3.2.12 on 2022-03-15 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelerapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
